### ISSUE TITLE
get 'ValueError: invalid literal for int() with base 10' message

### ISSUE THREAD

**Issue by askia318** [kwonmha/Improving-RNN-recommendation-model#4]
Hello, I download movielens dataset 1m from https://grouplens.org/datasets/movielens/1m/
and use preprocess.py to process ratings.dat, as your command shown in the page. 

And I got a folder called ratings containg data, models and results subfolders, everything in great! 

However, when I type python train.py -fr tf -d ...ratings\ I got error message: ValueError: invalid literal for int() with base 10: '2000-12-31'
The data themselves are from preprocess.py, how can I fix it? thanks.

**Comment by kwonmha** [comment]
Let me know where the error occurred.
I guess in 188th line of data_handling.py?
If so, use 187th line by uncommenting the line and commenting 188th line.

**Comment by askia318** [comment]
Yes. and I will try. Thanks. Tell you the result tomorrow.

**Comment by askia318** [comment]
Hello, after commenting 188th line and using 187th line, I got a message:

(tensorflow) C:\Users\cc.li\Documents\Improving-RNN-recommendation-model-master>python train.py -fr tf -d ml-1m\ratings\
2018-09-14 07:47:26.185922: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\cc.li\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Opening file (1)

it did not show error, but takes a very long time to process, has not yet stooped.

**Comment by kwonmha** [comment]
I think the training started correctly.
And I usually stopped the process by control+c on anaconda prompt.
And if your tensorflow uses only cpu, it will take a lot longer than using gpu.
(doesn't exactly know how much more)

**Comment by kwonmha** [comment]
Close as this issue is inactive.
