### ISSUE TITLE
there is no attribute or method named "self.tarining"

### ISSUE THREAD

**Issue by shwangdev** [kwonmha/Improving-RNN-recommendation-model#5]
https://github.com/kwonmha/Improving-RNN-recommendation-model/blob/9f690114f1486e1c71734752196970b794a80acd/neural_networks/rnn_base.py#L208

there is no attribute or method named "self.tarining"

**Comment by kwonmha** [comment]
You're right.
It should be self.training.
I'll fix that asap.
Thx.

**Comment by shwangdev** [comment]
Actually, when I enabled save_log with "-fr=tf" , it did not work. 
I did not dig into the root cause of that failure, but you may reproduce that failure.

**Comment by kwonmha** [comment]
Fixed the 2 bugs.
Check it out.
